### ISSUE TITLE
@casl/mongoose:  TS2430: Interface 'AccessibleSchema' incorrectly extends interface 'Schema'.

### ISSUE THREAD

**Issue by makslevental** [stalniy/casl#103]
error

```
node_modules/@casl/mongoose/index.d.ts:21:18 - error TS2430: Interface 'AccessibleSchema' incorrectly extends interface 'Schema'.
  Types of property 'plugin' are incompatible.
    Type '(plugin: (schema: Schema) => void) => this' is not assignable to type '{ (plugin: (schema: Schema) => void): this; <T>(plugin: (schema: Schema, options: T) => void, opts: T): this; }'.
      Types of parameters 'plugin' and 'plugin' are incompatible.

21 export interface AccessibleSchema extends mongoose.Schema {
```
deps

```
    "@casl/mongoose": "^2.1.2",
    "typescript": "^3.0.1"
```

**Comment by stalniy** [comment]
Thanks for the issue! I'll check this tomorrow

**Comment by miniplus** [comment]
This issue is blocking my [nestjs](https://github.com/nestjs/nest) project from building using the given script: `npm run start:prod` (as the tsc stops compiling because of the error thrown). I'm trying to look for a solution, but my knowledge only goes as far.

As this is a third party lib, this is unfortunately holding me back at the moment.

Trying to look for a workaround and/or proper solution, but any help from whoever is appreciated 😃

**Comment by stalniy** [comment]
I will try to solve the issue this weekend

**Comment by miniplus** [comment]
PR added @stalniy, would highly appreciate a merge and publish of the package if it's ok. (as it's still blocking me atm).
