### ISSUE TITLE
Question: Can I use it with React + Redux? Can some please provide an example?

### ISSUE THREAD

**Issue by btechgroup** [stalniy/casl#141]
Hi, can casl be used with the Redux Provider (Store).  can somebody please provide me a working example?

**Comment by stalniy** [comment]
Hi,

Sure, you can use. But what is your usecase? 

I don’t think you need to do some specific integration. But again it depends on what you want to do because the main goal of ACL on UI side is to provide consistent UX, not to confuse user with functionality which he is not allowed to use. In that cases CASL/react package should cover almost every usecase.

**Comment by stalniy** [comment]
You can also check #148 for some details of how to update ability from redux state.

Close this due to inactivity.
