### ISSUE TITLE
Custom sift expressions

### ISSUE THREAD

**Issue by thejuan** [stalniy/casl#149]
The latest version of sift has removed the global .use
What is the guidance for adding custom operators that we want to use with casl now?

**Comment by stalniy** [comment]
**The short answer**

Custom sift expressions has been never a feature of CASL. So, the short answer there is no guidance :)
I actually had strategic plans to move into [mingo](https://github.com/kofrasa/mingo) but for now it's a bit heavyweight in size.

**The longer answer**:

I checked sift changelog and see that you still can pass custom operators but as a 2nd argument into `sift` function. So, to make your code work you can create a custom `Rule` class which `Ability` instance will use to check conditions. This is undocumented feature right now because I wanted to weigh all pros and cons. But at least for time being you can use it achieve what you want. 

I haven't tested this but it should work

```js
import { Ability, Rule } from '@casl/ability'
import sift from 'sift'

const CUSTOM_OPERATORS = {
  $customOperator() { 
     // sift docs https://github.com/crcn/sift.js#custom-expressions
  }
}

class CustomRule extends Rule {
  constructor(...args) {
    super(...args)
    this._matches = this.conditions ? sift(this.conditions, { expressions: CUSTOM_OPERATORS }) : null
  }
}

const ability = new Ability([], { RuleType: CustomRule })
```

**Comment by stalniy** [comment]
I have never considered this to be a built-in feature of CASL because 
1. In case of sharing permissions between UI/API/microservices, it requires to share/reimplement them on each side
2. It prevents easy conversion of this custom operators in database query (what `@casl/mongoose` does for example). So, it requires to create custom logic for conversion into db query which may not be efficient enough

**Comment by thejuan** [comment]
Thanks, I'll look at custom rules.
We already have to share casl across the projects, adding an operators dependency isn't a big deal for us.

The operator is a DB operator for us, we have implemented the Postgres ltree operator so it can be used in queries and in permission checks.

**Comment by stalniy** [comment]
Sounds interesting! So I close this
