### ISSUE TITLE
Breaking CSS Style of third party components

### ISSUE THREAD

**Issue by rahulpsd18** [stalniy/casl#211]
Hi,

First of all, thanks for the awesome library.

I am unable to keep the style when of my sidebar when using `<Can/>`. I am using [`antd`](https://ant.design/components/layout/) to create a sidebar in my app but when I try to conditionally show a menu item based on user's ability, the styles get broken. 

How can I make use of `<Can/>`without breaking the css child combinator styles `(.parent > .child > .child2)`?

My Code:
```typescript
<Sider>
    <div className="logo" />
    <Menu theme="dark" mode="inline" defaultSelectedKeys={['1']}>
        <Can I="view" a="applications"> 
            <Menu.Item key="1"> // broken styles as child combinator is not found
                <Icon type="app" />
                <span>Applications</span>
            </Menu.Item>
        </Can>
        <Menu.Item key="2">
            <Icon type="settings" />
            <span>Settings</span>
        </Menu.Item>
    </Menu>
</Sider>
```

**The `<li>` element generated in case of `<Can/>` has class "undefined-item" instead of "ant-menu-item", as in case of normal `<Menu.Item>`.**

Using the following versions:
```
"@casl/ability": "^3.1.2",
"@casl/react": "^1.0.3",
"react": "^16.8.6",
"antd": "^3.20.6",
```

**Comment by stalniy** [comment]
Hi,

How did you create `<Can>` (`createContextualCan` or `createBoundCan`)?

**Comment by rahulpsd18** [comment]
```
export const Can = createCanBoundTo(ability);
``` 
where **createCanBoundTo** was imported from `@casl/react`.

I also tried the **createContextualCan** folloing the [readme](https://github.com/stalniy/casl/tree/master/packages/casl-react#1-scoping-can-to-use-a-particular-ability) but met the same fate.

**Comment by stalniy** [comment]
<Can> uses React Fragment if available. Probably what I can do is to check if there is exactly one child node then render it directly and if there are more then render in fragment

**Comment by rahulpsd18** [comment]
That would indeed solve my issue. Thanks!

**Comment by stalniy** [comment]
After some inverstigation, there is nothing I can do with `<Can>` component to make this stuff work properly due to how `rc-menu` works. `rc-menu` is a lib which is used by antd for menus.

That `<Menu>` goes over all children, clones them and pass additional properties. When you add `<Can>` as a child of `<Menu>`, `<Can>` receive all props which were supposed to be passed into `<Menu.Item>`. That's why you can incorrect class and actually not only :) There are other state management callbacks which are passed to `<Menu.Item>`  from `<Menu>`.

So, it's not a fault of `<React.Fragment>`. And that changes won't help. There is potential workaround which I don't like:

```jsx
<Can ...>{(isAllowed, ability, ...restProps) => <Menu.Item {...restProps}>}</Can>
```

**What can you do to make things work?**

Instead of `<Can>` component you can get `Ability` instance directly from React's context API. There are 2 options:
* [`useContext` hook](https://reactjs.org/docs/hooks-reference.html#usecontext)
* [`contextType`](https://reactjs.org/docs/context.html#classcontexttype)

I updated [`@casl/react` README]() with that suggestions.

Your code in this case will look like this:

```jsx
<Sider>
    <div className="logo" />
    <Menu theme="dark" mode="inline" defaultSelectedKeys={['1']}>
        { ability.can('view', 'applications') &&
            <Menu.Item key="1">
                <Icon type="app" />
                <span>Applications</span>
            </Menu.Item>
        }
        <Menu.Item key="2">
            <Icon type="settings" />
            <span>Settings</span>
        </Menu.Item>
    </Menu>
</Sider>
```

**Comment by stalniy** [comment]
Close this as there is nothing I can do more with this. You can check my example here: https://codesandbox.io/s/admiring-field-dxc5t

**Comment by rahulpsd18** [comment]
@stalniy Thanks for the help. I really appreciate you looking at it.
