### ISSUE TITLE
Return empty casl file.

### ISSUE THREAD

**Issue by Anichauhastorm** [stalniy/casl#239]
I gave a permission to user for add data in a model.
`In [124]: user.has_perm('cities.add_city') `
`Out[124]: True`

but i did not get any casl file when call.
`In [123]: user.casl_permissions.values()'                                                                                                                                              
'Out[123]: <UserPermissionQuerySet []>'

**Comment by stalniy** [comment]
Could you please provide more information?

Steps to reproduce,  some code, ideally working example on codesanbox. Otherwise I won’t be able to help you

**Comment by Anichauhastorm** [comment]
A user has a permission to add field in model and i want to get casl file.

**Comment by stalniy** [comment]
I don’t know what you mean by saying `to get casl file`. Which file? :)

I need some code:
1. Show me how you setup permissions
2. How you check permissions
3. Where the issue is

I don’t know what `user.has_perm` is. This is definitely is not part of this lib. `UserQueryPermissionSet` is also not known for me type. 

Is this a JavaScript?

**Comment by stalniy** [comment]
Close as stale.

Thanks for trusting casl
