### ISSUE TITLE
Best way to check if one ability is true?

### ISSUE THREAD

**Issue by vemundeldegard** [stalniy/casl#285]
Hey!

First of all, just a round of applause for this great library and the new version. 

I where wondering if there is a simple way to check if you can do one of multiple actions on a subject? I where looking in the documentation, but couldn't find anything. 

I where thinking something like ability.can("read write", "Article"), but that wouldn't make sense in terms of TypeScript.

**Comment by stalniy** [comment]
Duplicate of #278 

CASL doesn't support "OR" and "AND" logic in its parameters because it's hard to express so that it's clear for everybody (if you pass an array some people may assume OR logic and other AND).

CASL supports AND logic through aliases, so probably OR logic is not so bad to be represented as an array

**Comment by stalniy** [comment]
Sorry for sound a bit like a machine, it was a long day :) any suggestions or PRs are very welcome.

**Comment by vemundeldegard** [comment]
Ok! No worries. I can just create my own way of checking multiple abilities. Aliases is also a good solution. Thanks! :)

**Comment by stalniy** [comment]
Just use logical OR for now. I remember this is not easy because also requires changes in types.

 currently casl support per action subjects. For example User can be only updated and created but BlogPost also can be deleted. 
 
And this makes more headache to support string or string[] and per action subject
