### ISSUE TITLE
How does CASL compare to Casbin

### ISSUE THREAD

**Issue by IGassmann** [stalniy/casl#306]
How does CASL compare to [Node-Casbin](https://github.com/casbin/node-casbin) in terms of capabilities and features?

Observation: it would be nice to have the answer to this question documented in the docs.

**Comment by stalniy** [comment]
You can find some comparison in [CASL presentation](https://www.slideshare.net/SergiyStotskiy/casl-isomorphic-permission-managementpptx-207064469), slide №28 and №29.

This all I can do because I don't have experience with casbin. What I don't like about it is configuration files and custom syntax. CASL is just old plain JavaScript

**Comment by stalniy** [comment]
I don't plan to create to document this comparison because it will require additional efforts to sync this page with the latest changes in casbin or similar libraries.

CASL is the mostly used Nodejs library for ACL for now. You can check [npmtrends](https://www.npmtrends.com/@casl/ability-vs-casbin) for some insights.
