### ISSUE TITLE
Add performance description to the documentation

### ISSUE THREAD

**Issue by enheit** [stalniy/casl#323]
As a user I would like to have a performance description in README file so that I can compare this library with other approaches.

How does CASL is looking for the rule inside Abilities? And how much time it takes? O(n) or O(1)?

**Comment by stalniy** [comment]
Good point. However I’d say it depends. 

If it’s creation time, it’s  O(n). Casl builds a hash map under the hood to speed up the actual checks. 

If it’s a check by subject type, it’s a constant time because it gets the 1st rule for pairs of action and subject from the hashmap.

If it’s a check by subject (i.e., object), it depends on the operators you use and implementation of external library in my case sift.js. I need to double check this

**Comment by stalniy** [comment]
n - amount of rules obviously

**Comment by stalniy** [comment]
So, finally:

* ability creation time - O(n) (n - amount of rules)
* check by action and subject type (e.g., `ability.can('read', 'Todo')`) - O(1)
* check by action and subject object (e.g., `ability.can('read', todo)`) - O(k) + O(m) + O(p), where: 
  k - is amount of rules for the same pair of action and subject
  m - amount of operators in conditions
  O(p) - complexity of used operators.

@enheit What do you think about this estimation?

**Comment by enheit** [comment]
That is exactly what I was looking for. Thank you.

Would be nice to have such information in the documentation.

**Comment by stalniy** [comment]
Added in `@casl/ability` README - https://github.com/stalniy/casl/tree/master/packages/casl-ability#5-performance-and-computational-complexity
