### ISSUE TITLE
Using `toMongoQuery` in `@casl/mongoose` without installing mongoose

### ISSUE THREAD

**Issue by exptom** [stalniy/casl#493]
We are using Casl with mongodb but not via mongoose. We are making use of the `toMongoQuery` method as described in your README to generate queries. However we do not need the mongoose package. Because you require mongoose in the file that defines `toMongoQuery` we still have to install mongoose even though the `toMongoQuery` method doesn't use mongoose. Is there any way this could be resolved?

**Comment by stalniy** [comment]
I can make `mongoose` optional but then it does not make much sense because the main purpose of this package is to support mongoose integration. `toMongoQuery` function is very small, so for such rare use case you can just [copy/paste it](https://github.com/stalniy/casl/blob/master/packages/casl-mongoose/src/mongo.ts) in your app code. All the heavy-lifting is done by `@casl/ability/extra` package.

I'm sorry but at least for now I don't plan to do anything with this.

**Comment by stalniy** [comment]
Feel free to comment if you have some ideas on how to fix it

**Comment by rubybb** [comment]
I suggest considering moving ``toMongoQuery`` to ``@casl/ability/extra``?
