### ISSUE TITLE
checking ability with conditions produces TS error

### ISSUE THREAD

**Issue by ianatha** [stalniy/casl#550]
I'm getting a peculiar TS error when attempting to check abilities using a condition. Specifically,

`userAbility.can(Action.Read, subject("user", { id: current_user_id })))` throws the TS error:
```
Argument of type '{ id: any; } & ForcedSubject<"user">' is not assignable to parameter of type 'AppSubjects'.
  Type '{ id: any; } & ForcedSubject<"user">' is not assignable to type 'Model<linked_item, "linked_item">'.
    Type '{ id: any; } & ForcedSubject<"user">' is missing the following properties from type 'linked_item': user_id, institution_id
```

In the `userAbility.can(Action.Read, subject("user", CONDITIONS)))` invocation, I'd expect `CONDITIONS` to be of type `Prisma.userWhereInput`, but it seems it's not.

My AppSubjects type is defined as:
```
import { institution, linked_item, user } from "@prisma/client";
import { Subjects } from '@casl/prisma';

export type AppSubjects = Subjects<{
    user: user,
    institution: institution,
    linked_item: linked_item,
}> | 'all';
```

(`user` and `institution` have an `id`, but `linked_item` doesn't.)

Defining the ability compiles just fine:
```
createAbilityForUser(user: UserDto) {
    const { can, build } = new AbilityBuilder<AppAbility>(Ability as AbilityClass<AppAbility>);

    if (user.is_admin === true) {
        can(Action.Manage, 'all');
    }

    can(Action.Read, 'user', { id: user.id });
    can(Action.Update, 'user', { id: user.id });

    return build();
  }
```

My current workaround is to append ` | { id: string }` to each value in `AppSubjects` but it seems like I'm missing something. Could you please provide any guidance?

I'm using `"@casl/prisma": "^1.0.0"`, and I tried with all of `prisma` `3.0.2`, `2.30.3`, and `2.14.0`.

**Comment by stalniy** [comment]
the 2nd argument of `ability.can` is a subject (i.e., context) not conditions. You use conditions to enforce permissions on a subject (usually domain entity). And typescript forces you to pass all the properties from the model because at checking time you don't know what actual permissions are. Today it's just an `id` check but tomorrow it can be something else.

So, works as expected.

**Comment by raminious** [comment]
Before finding this issue, I was having the same error. 
I think it's better to mention that in the documentation 

![image](https://user-images.githubusercontent.com/334716/147872434-4bb84498-d2aa-40a0-b5bc-3ac0bf5ca88f.png)

**Comment by raminious** [comment]
@stalniy

**Comment by stalniy** [comment]
It’s very strange to me that people are trying to pass conditions to check. Why is it strange? Because if casl would require to pass conditions, then we would loose the whole point of this abstraction :) casl encapsulates conditions in single place. They can be anything and then you can change everything in a single place without touching feature specific code.  

So, by passing conditions into `can` check you still use a wrong mental model which actually translates to hard coded `if` checks just written in a fancy way:

```
ability.can(“read”, { id: { $in: [1,2] }, type: “Post” })
// is the same as
if ([1,2].includes(user.id)) ...

// but not the same as!!!
ability.can(“read”, article) // were article is a domain model
```

In docs, you will not find an example that checks permissions on conditions. Additionally, there are multiple example repos were models are used as subjects. 

So, I don’t believe documentation updates will help here. Maybe video course
