### ISSUE TITLE
Defining abilities with conditions does not work in NestJS w/ prisma

### ISSUE THREAD

**Issue by MarcieMarc425** [stalniy/casl#641]
**Describe the bug**

Currently, if i define an ability with just two params: `cannot(Action.Update, 'User')` - this will work fine. However, if I add a condition to the ability: `cannot(Action.Update, 'User', { id: user.id })` - which means the user should not be able to update a User object that has his own id, but this does not really work. Depending on whether I use `can` or `cannot`, it will always return either true or false.

**To Reproduce**

This is my ability factory where I define the abilities.

```typescript
import { AbilityBuilder, AbilityClass } from '@casl/ability';
import { PrismaAbility, Subjects as CaslPrismaSubjects } from '@casl/prisma';
import { Injectable } from '@nestjs/common';
import { User } from '@prisma/client';

export enum Action {
  Manage = 'manage',
  Create = 'create',
  Read = 'read',
  Update = 'update',
  Delete = 'delete',
}

export type Subjects = CaslPrismaSubjects<{ User: User }>;
export type AppAbility = PrismaAbility<[Action, Subjects]>;
const AppAbility = PrismaAbility as AbilityClass<AppAbility>;

@Injectable()
export class CaslAbilityFactory {
  createForUser(user: User) {
    const { can, cannot, build } = new AbilityBuilder(AppAbility);

    if (user.role === UserType.EMPLOYEE) {
      can(Action.Manage, 'User'); // Employees can do everything on User
    } else {
      can(Action.Manage, 'User');
      cannot([Action.Read, Action.Update], 'User', { NOT: { id: user.id } }); // User can only read and update their own user data
    }

    return build();
  }
}
```

This is the guard where I get the current user trying to do the request. I also followed the doc for `casl/prisma` to make sure to use a subject adapter imported from `@casl/ability`.

```typescript
import { ForbiddenError, subject } from '@casl/ability';
import {
  ForbiddenException,
  Inject,
  Injectable,
  InternalServerErrorException,
  type CanActivate,
  type ExecutionContext,
} from '@nestjs/common';
import { Reflector } from '@nestjs/core';
import { CaslAbilityFactory } from '../casl/casl-ability.factory';
import { CHECK_POLICIES_KEY, PolicyHandler } from '../decorators/check-policies.decorator';

@Injectable()
export class PoliciesGuard implements CanActivate {
  constructor(
    @Inject(Reflector) private reflector: Reflector,
    @Inject(CaslAbilityFactory) private caslAbilityFactory: CaslAbilityFactory,
  ) {}

  async canActivate(context: ExecutionContext): Promise<boolean> {
    const policyHandlers =
      this.reflector.get<PolicyHandler[]>(CHECK_POLICIES_KEY, context.getHandler()) || [];

    const { user } = context.switchToHttp().getRequest();
    const ability = this.caslAbilityFactory.createForUser(user);

    try {
      policyHandlers.forEach((rule) => {
        ForbiddenError.from(ability).throwUnlessCan(rule.action, subject('User', user)); // need to use subject adapter for Prisma conditions
      });

      return true;
    } catch (error) {
      if (error instanceof ForbiddenError) {
        throw new ForbiddenException(error.message);
      }
      throw new InternalServerErrorException(error);
    }
  }
}
```

The user object that is fetched from request, as well as the database model is as follows:
```typescript
{
  id: 'id1',
  role: UserType.Customer, // or UserType.Employee
  name: 'name1'
}
```

The above will accept all read and update actions regardless of the user id, even if I try to hardcode either the condition or the user object passed to the subject adpater.

**Expected behavior**

In above example, I expect the defined behavior to allow users who are not of employee type to be able to `manage` USERS, but for `create` and `update` actions, the users should only be able to do so if has the same `user.id`, in other words, the users themselves.

**CASL Version** 

`@casl/ability` - v5.4.4
`@casl/prisma` - v1.0.2
`prisma` - v3.15.0
`@prisma/client` - v3.15.0
`@nestjs` - v9.0.0

**Environment**:

`nodejs`: v16.6.0
`typescript`: v4.7.2

**Comment by stalniy** [comment]
not a bug. it should be:

```ts
if (user.role === UserType.EMPLOYEE) {
      can(Action.Manage, 'User'); // Employees can do everything on User
    } else {
      can(Action.Manage, 'User');
      cannot([Action.Read, Action.Update], 'User', { id: user.id }); // User can only read and update their own user data
    }
```

When you define a direct rule without condition it overrides all other rules with conditions. that's why:

```
can(Action.Manage, 'User');
can([Action.Read, Action.Update], 'User', { NOT: { id: user.id } }); 
```

Always returns `true`, Because you say:
1. can manage any user
2. can read and update users that are not this user

Later this conditions are OR-ed and you get always true. That's why general rules without conditions needs to be combined with inverted ones. Re-check docs please for further details

**Comment by mareksl** [comment]
Not sure if this is connected to this, but I'm still struggling to see how I can express: "A `User` cannot manage any `Account`s, except if some condition is met (e.g. field `userId` is equal to `User`'s `id`)"

My rules are:
```ts
cannot(Action.Manage, Account);
can(Action.Read, Account, { userId: user.id });
```
`ability.can(Action.Manage, exampleAccount)` works well when used with an instance of `Account` (if `userId` matches, it returns `true`, but `false` if it doesn't)

However, when called with the `Account` class directly, `ability.can(Action.Read, Account)` always returns `true`, or always `false` if I reverse the second condition to `cannot(Action.Read, Account, { userId: { $ne: user.id } })`.
I would assume it would false, since there is no `userId` on the class itself. Am I wrong here?

**Comment by MarcieMarc425** [comment]
Hmm, but in the example I have given, I wrote:

```typescript
can(Action.Manage, 'User');
cannot([Action.Read, Action.Update], 'User', { NOT: { id: user.id } });  // User can only read and update their own user data
```

Note the double negative in the example. This produces the result of always returning true. In this case, wouldn't the rules translate to following logic?:
1. Can manage any user
2. Cannot read and update users that **ARE NOT** this user

I have also tried your provided code. However, this produces the result of always returning false (forbidden). In your example, wouldn't the rules translate to following logic?:
1. Can manage any user
2. Cannot read and update user that **IS** own user

**Comment by mareksl** [comment]
Not sure if this applies here, but I had a similar problem, where I was confused by the way casl works, especially this part:

> But CASL is different! It allows us to ask different questions to our permissions. So, when you check on a
> 
> - subject, you ask "can I read THIS article?"
> - subject type, you ask "can I read SOME article?" (i.e., at least one article)
> It's very useful when you don't have an instance to check but know its type (for example, during creation), so this allows your app to fail fast.
> 
> > If you do checks on a subject type, you need to check permissions one more time on the final subject, right before sending request to API or database.

https://casl.js.org/v6/en/guide/intro#checking-logic

I thought checking ability for the `Account` class itself (not an instance) would return `false` for these rules:
```ts
cannot(Action.Manage, Account);
can(Action.Manage, Account, { userId: user.id });
```
since the class itself does not have a `userId`, but it always returned `true` (or always `false` when I inverted the rules). It turns out that's the correct behavior, so now I also have to check the instance once it's returned, which makes perfect sense once I finally figured it out. :sweat_smile:
Perhaps this could be highlighted a bit more in the docs?

**Comment by stalniy** [comment]
this is how I test it:

```ts

export enum Action {
  Manage = 'manage',
  Create = 'create',
  Read = 'read',
  Update = 'update',
  Delete = 'delete',
}

export type Subjects = CaslPrismaSubjects<{
    User: User;
    DbMessage: DbMessage;
    // Post: Post;
}>;
export type AppAbility = PrismaAbility<[Action, 'all' | Subjects]>;
const AppAbility = PrismaAbility as AbilityClass<AppAbility>;


const user: User = {
  id: 1,
  role: 'customer', // or UserType.Employee
}

const anotherUser: User = {
  id: 2,
  role: 'customer'
}

const { can, cannot, build } = new AbilityBuilder(AppAbility);

can(Action.Manage, 'User');
cannot([Action.Read, Action.Update], 'User', {
  NOT: { id: user.id }
}); // User can only read and update their own user data

const ability = build();

console.log({
  canReadItself: ability.can(Action.Read, subject('User', user)),
  canReadOthers: ability.can(Action.Read, subject('User', anotherUser)),
  canReadAtLeastOneUser: ability.can(Action.Read, 'User')
});

// results
{
  canReadItself: true,
  canReadOthers: false,
  canReadAtLeastOneUser: true
}
```

all works as expected
