### ISSUE TITLE
update documentation for Ability and PrismaAbility in AbilityBuilder examples, coz they are deprecated

### ISSUE THREAD

**Issue by robertsi** [stalniy/casl#685]
**Is your feature request related to a problem? Please describe.**
Examples on https://casl.js.org/v6/en/package/casl-prisma and https://casl.js.org/v6/en/guide/define-rules are deprecated

**Describe the solution you'd like**
Please update AbilityBuilder examples with  createMongoAbility and createPrismaAbility, I have no idea atm how to use them, but I have started using casl today. Got examples working with deprecation warnings atm.

**Comment by ambiguous48** [comment]
@stalniy Thank you for maintaining this library.

I'm trying to migrate from the deprecated `PrismaAbility` to the new `createPrismaAbility`. The docs still use `PrismaAbility`, but I'm not sure if that's because `createPrismaAbility` is new and hadn't yet made it into the prisma examples in the docs, or if it is not meant to replace the deprecated `PrismaAbility`.

How is `createPrismaAbility` supposed to be used? I'm not generating the prisma client into a custom directory, just trying to migrate away from the deprecated function. Tried to follow the mongo example linked in this thread, but couldn't really make it work.
