### ISSUE TITLE
rule without condition not honored when instance provides one

### ISSUE THREAD

**Issue by Morriz** [stalniy/casl#700]
**Describe the bug**
Like title says. See repro below:

**To Reproduce**
1. Ability configuration (rules, detectSubjectType, etc)
```json
{
  action: "read",
  sub: "App",
}
3. How do you check abilities

**Expected behavior**
A clear and concise description of what you expected to happen.

**Interactive example** (optional, but highly desirable)
provide a link to the example from http://repl.it/, https://codesandbox.io/ or similar, so we can quickly test and provide feedback. Otherwise

**CASL Version**

<!-- leave packages which you use -->

`@casl/ability` - v
`@casl/vue` - v
`@casl/react` - v
`@casl/angular` - v
`@casl/aurelia` - v

**Environment**:
<!-- Nodejs version or Browser version or TypeScript version -->

**Comment by stalniy** [comment]
I don’t understand the issue. What is “Instance”? Why does some instance provide a rule?

Frankly speaking, if you don’t care creating a proper issue request, why should I spend time trying to understand it?

Please  provide more details, at least code snippet of what you trying to do. Otherwise I’ll close it as incorrectly created

**Comment by Morriz** [comment]
Sry, I did not even know I submitted this while I was preparing a code sandbox. Mistake!
