### ISSUE TITLE
Ability.cannot doesn't work with Objects

### ISSUE THREAD

**Issue by LowM4N** [stalniy/casl#9]
I'm trying to use CASL with Feathers and RethinkDB. My problem is that I can't get it working with conditions, like the user can only access own data.

I have this [guide](https://blog.feathersjs.com/authorization-with-casl-in-feathersjs-app-fd6e24eefbff) as reference and the only difference is, that I'm not using MongoDB or Mongose Models.

I'm digged in your [Code](https://github.com/stalniy/casl/blob/54bc614bfc6d6e226089b7749e7da007cb6de4e3/src/ability.js#L90-L105), but I don't understand where you are checking your conditions from the rules.

```
import { AbilityBuilder, Ability } from 'casl'
import { Forbidden } from 'feathers-errors'

function defineAbilitiesFor(user) {
  const { rules, can, cannot } = AbilityBuilder.extract()

  console.log('define abilities for: ', user ? user.email : 'anonymous')

  if (user) {
    can(['get'], 'users', { id: user.id })
  } else {
    // anonymous
  }

  return new Ability(rules)
}

export default function authorize(name = null) {
  return async function(hook) {
    const action = hook.method
    const service = name ? hook.app.service(name) : hook.service
    const serviceName = name || hook.path

    hook.params.ability = defineAbilitiesFor(hook.params.user)

    const params = Object.assign({}, hook.params, { provider: null })
    const result = await service.get(hook.id, params)

    // works with (action, name) but without condition
    if (hook.params.ability.cannot(action, result)) {
      throw new Forbidden(`You are not allowed to ${action} ${serviceName}`)
    }

    return hook
  }
}
```

I'm getting every time a forbidden, only when I'm replacing the result with name in the cannot call, then it works as expected but without conditions.

Doing I something wrong or what is the problem?

**Comment by stalniy** [comment]
Hi, thanks for your interest to casl! 

You can check all rules by calling `ability.rules`.  Does rethinkDB ObjectId representation in js has a `toString` method which converts if id into string value?

Casl currently uses `sift.js` package to check rule conditions

**Comment by stalniy** [comment]
Also I don't see in your code `subjectName` function which detects object type. So, I guess casl just can't determine the type of the object (whether its `users` or whatever else. feathers' services returns plain objects and default type detection logic can determine only types of custom objects or mongoose models).

That's why in the example there is a [custom function](https://github.com/stalniy/casl-feathersjs-example/blob/master/src/hooks/abilities.js#L9) `subjectName` which then [passed to](https://github.com/stalniy/casl-feathersjs-example/blob/master/src/hooks/abilities.js#L27) `Ability` constructor. And additionally I used `Symbol` [to define object type](https://github.com/stalniy/casl-feathersjs-example/blob/master/src/hooks/abilities.js#L74) on plain object which is then checked by `subjectName`.

I don't see this logic in your example, so this should be an issue if you don't have it

**Comment by LowM4N** [comment]
@stalniy thank you for your response, the problem was that I used only plain objects.

**Comment by stalniy** [comment]
Great!

So, can we close this now?

**Comment by LowM4N** [comment]
@stalniy yes, you can close it.
